DISTDIRS = 
DIRS = webgraphic
ZIPDIR = /tmp/LaTeXML
ZIPS = 
STY = 
PACKAGE = 

all ltxml package doc filedate checksum enablechecksum disablechecksum ltds: 
	@for d in $(DIRS); do (cd $$d && $(MAKE) -$(MAKEFLAGS) $@) done
