# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LaTeXML
version:      0.4.0
version_from: lib/LaTeXML.pm
installdirs:  site
requires:
    Image::Magick:                 0
    Parse::RecDescent:             0
    XML::LibXML:                   1.57
    XML::LibXML::XPathContext:     0
    XML::LibXSLT:                  1.57

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
